name: backpack
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk:  ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^1.1.2
  argon_buttons_flutter: ^1.0.6
  auto_route: ^0.6.9
  bloc: ^6.1.1
  christian_picker_image: ^0.1.8
  circular_profile_avatar: ^1.0.8
  cloud_firestore: ^0.16.0
  connectivity_wrapper: ^1.0.4
  cupertino_icons: ^1.0.1
  cupertino_radio_choice: ^1.0.1+1
  equatable: ^1.2.6
  expandable: ^4.1.4
  firebase_core: ^0.7.0
  flutter_bloc: ^6.1.2
  flutter_native_splash: ^0.3.0
  flutter_secure_storage: ^3.3.5
  flutter_slidercarousel: ^0.0.1+3
  flutter_spinkit: ^4.1.2+1
  flutter_xlider: ^3.4.0
  formz: ^0.3.2
  gap: ^1.2.0
  intl: ^0.17.0
  nice_intro: ^0.1.4
  pedantic: ^1.9.2
  perspective_pageview: ^0.1.1
  progress_dialog: ^1.2.4
  sliding_card: ^0.1.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  very_good_analysis: ^1.0.4
  auto_route_generator: ^0.6.10
  build_runner: any
  mockito: ^4.1.4
  r_flutter: ^0.6.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 700
    - family: stn
      fonts:
        - asset: assets/fonts/sfns-otf/SFNSDisplay-Bold.otf
        - asset: assets/fonts//sfns-otf/SFNSDisplay-Regular.otf
          weight: 700
